INSERT INTO `categories` (`id`, `name`, `parent_id`) VALUES 
(NULL, 'Electronics', NULL),
(NULL, 'Cars', NULL),
(NULL, 'Furniture', NULL),
(NULL, 'Garden', NULL),
(NULL, 'Office', NULL),
(NULL, 'Services', NULL),
(NULL, 'Smartphones', '1'),
(NULL, 'Laptops', '1'),
(NULL, 'Televisions', '1'),
(NULL, 'Fuel Cars', '2'),
(NULL, 'Hybrid Cars', '2'),
(NULL, 'Electric Cars', '2'),
(NULL, 'Sofas', '3'),
(NULL, 'Beds', '3'),
(NULL, 'Chairs', '3'),
(NULL, 'Garden Furniture', '4'),
(NULL, 'Outdoor Lighting', '4'),
(NULL, 'Plants & Flowers', '4'),
(NULL, 'Office Chairs', '5'),
(NULL, 'Desks', '5'),
(NULL, 'Stationery', '5'),
(NULL, 'Consulting', '6'),
(NULL, 'Repair Services', '6'),
(NULL, 'Delivery Services', '6'),
(NULL, 'Appliances', NULL),
(NULL, 'Clothing', NULL),
(NULL, 'Toys', NULL),
(NULL, 'Books', NULL),
(NULL, 'Music', NULL),
(NULL, 'Gaming', NULL),
(NULL, 'Refrigerators', '1'),
(NULL, 'Washing Machines', '1'),
(NULL, 'Microwaves', '1'),
(NULL, 'Men\'s Clothing', '2'),
(NULL, 'Women\'s Clothing', '2'),
(NULL, 'Children\'s Clothing', '2'),
(NULL, 'Action Figures', '3'),
(NULL, 'Board Games', '3'),
(NULL, 'Dolls', '3'),
(NULL, 'Fiction', '4'),
(NULL, 'Non-Fiction', '4'),
(NULL, 'Comics', '4'),
(NULL, 'Instruments', '5'),
(NULL, 'CDs & Vinyl', '5'),
(NULL, 'Music Accessories', '5'),
(NULL, 'Consoles', '6'),
(NULL, 'Games', '6'),
(NULL, 'Gaming Accessories', '6');
