INSERT INTO `categories` (`id`, `name`, `parent_id`) 
VALUES 
    (NULL, 'Electronics', NULL),
    (NULL, 'Cars', NULL),
    (NULL, 'Furniture', NULL),
    (NULL, 'Garden', NULL),
    (NULL, 'Office', NULL),
    (NULL, 'Services', NULL),
    (NULL, 'Clothing', NULL),
    (NULL, 'Toys', NULL),
    (NULL, 'Books', NULL),
    (NULL, 'Music', NULL),
    (NULL, 'Gaming', NULL);

INSERT INTO `categories` (`id`, `name`, `parent_id`) 
VALUES 
    (NULL, 'Smartphones', 1),
    (NULL, 'Laptops', 1),
    (NULL, 'Televisions', 1),
    (NULL, 'Appliances', 1),
    (NULL, 'Fuel Cars', 2),
    (NULL, 'Hybrid Cars', 2),
    (NULL, 'Electric Cars', 2),
    (NULL, 'Sofas', 3),
    (NULL, 'Beds', 3),
    (NULL, 'Chairs', 3),
    (NULL, 'Garden Furniture', 4),
    (NULL, 'Outdoor Lighting', 4),
    (NULL, 'Plants & Flowers', 4),
    (NULL, 'Office Chairs', 5),
    (NULL, 'Desks', 5),
    (NULL, 'Stationery', 5),
    (NULL, 'Consulting', 6),
    (NULL, 'Repair Services', 6),
    (NULL, 'Delivery Services', 6),
    (NULL, 'Men\'s Clothing', 7),
    (NULL, 'Women\'s Clothing', 7),
    (NULL, 'Children\'s Clothing', 7),
    (NULL, 'Action Figures', 8),
    (NULL, 'Board Games', 8),
    (NULL, 'Dolls', 8),
    (NULL, 'Fiction', 9),
    (NULL, 'Non-Fiction', 9),
    (NULL, 'Comics', 9),
    (NULL, 'Instruments', 10),
    (NULL, 'CDs & Vinyl', 10),
    (NULL, 'Music Accessories', 10),
    (NULL, 'Consoles', 11),
    (NULL, 'Games', 11),
    (NULL, 'Gaming Accessories', 11);